coverage:
  precision: 1
  round: down
  range: "50...80"
  
  ignore:
    - "tests/**/*"
    - "dist/**/*"
    - "scripts/**/*"
    - "*.config.*"
  
  status:
    project:
      default:
        target: 60%
        threshold: 10%
        if_ci_failed: error
    patch: off

comment:
  layout: "diff"
  behavior: default
  require_changes: false