coverage:
  ignore:
    - "test_data/**/*"
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch: off

comment:
  layout: "diff,flags,tree"
  behavior: default
  require_changes: true