version: 1
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: /var/log/app.log
    maxBytes: 10485760
    backupCount: 5

loggers:
  requests:
    level: WARNING
    handlers: [console]
    propagate: no
  
  urllib3:
    level: WARNING
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console, file]